# Generated by Django 5.2.4 on 2025-07-29 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField()),
                ('description', models.CharField()),
                ('rating', models.IntegerField()),
                ('slug', models.SlugField()),
                ('author', models.CharField()),
            ],
        ),
    ]
