# Generated by Django 5.2.4 on 2025-07-30 06:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Enter full name')),
                ('email_address', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('first_time_visit', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3, verbose_name='Is this the first time you have visited the site?')),
                ('reason_to_visit', models.TextField(verbose_name='What is your reason of visiting this site?')),
                ('user_friendlyness', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='How user friendly is this website?')),
                ('found_what_needed', models.CharField(choices=[('all', 'Yes, all of it'), ('some', 'Yes, some of it'), ('none', 'No, none of it')], max_length=10)),
            ],
        ),
    ]
