# Generated by Django 5.2.4 on 2025-07-30 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website_feedback_form', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WebsiteForm',
            new_name='WebsiteFormModel',
        ),
    ]
